final Map<String, String> expenseIconList = {
  'Food': 'assets/expense_trcker_icons/curry.png',
  'Rent': 'assets/expense_trcker_icons/rent.png',
  'Groceries': 'assets/expense_trcker_icons/grocery-cart.png',
  'Restaurants': 'assets/expense_trcker_icons/dinner-table.png',
  'Education': 'assets/expense_trcker_icons/education.png',
  'Subscriptions': 'assets/expense_trcker_icons/membership.png',
  'Bills': 'assets/expense_trcker_icons/bill.png',
  'Gifts': 'assets/expense_trcker_icons/gift.png',
  'Maintenance': 'assets/expense_trcker_icons/estate.png',
  'Bike Expenses': 'assets/expense_trcker_icons/utility.png',
  'Others': 'assets/expense_trcker_icons/other.png',
  'Transport': 'assets/expense_trcker_icons/bus.png',
  'Vacations': 'assets/expense_trcker_icons/beach.png',
};
